version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgresdb:
    image: postgres:14.19-alpine3.21
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass